name: zzbase images

on: [push]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: zzbase
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v3
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v2
        with:
          build-args: |
            IMG_VERSION=alpine:3.12.0
            NAS_USER=dnke
          context: .
          psuh: true
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.actor }}/${{ env.IMAGE_NAME }}
          tags: latest        
