on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: zzbase
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v1
        with:
          build-args: |
            IMG_VERSION=3.12.0
            NAS_USER=dnke
        
