on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: zzbase
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v1

