name: zzbase images

on: [push]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: zzbase
    steps:
      - name: "Build: checkout"
        uses: actions/checkout@v3

      - name: "build: set up socker buildx"
        uses: docker/setup-buildx-action@v2
        
      - name: "Build: login to GHCR"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: spongle70
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: "Build: build and push dockerimage"
        uses: docker/build-push-action@v3
        with:
          build-args: |
            IMG_VERSION=alpine:3.12.0
            NAS_USER=dnke
          context: .
          push: true
          #registry: ${{ env.REGISTRY }}
          #username: spongle70
          #password: ${{ secrets.GITHUB_TOKEN }}
          #repository: ${{ github.actor }}/${{ env.IMAGE_NAME }}
          tags: latest        
